#!/usr/bin/php
<?php detine('VENDOR', 'ckpunmkug');

define('PROJECT_NAME', 'framework');
define('PROJECT_DIR', realpath(__DIR__.'/..'));

set_include_path(PROJECT_DIR.'/include');

require_once('class/Args.php');
require_once('block/Args.php');

require_once('class/Main.php');
require_once('function/main.php');

$return = main($argv);
if($return !== true) {
	trigger_error("'main' call failed", E_USER_ERROR);
	exit(255);
}
exit(0);

