remote-control:
  control-enable: no

server:
	username: unbound
	interface-automatic: no
	interface: 127.0.0.1
	logfile: "/var/log/unbound/unbound.log"
	log-queries: yes
	log-replies: no
	log-tag-queryreply: yes
	verbosity: 0
	
	auto-trust-anchor-file: "/var/lib/unbound/root.key"
	val-permissive-mode: no
	
